### ISSUE TITLE
EMIKAT tables always show the same data

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/table-components#20]
Not sure if it's because of EMIKAT or because of the table component, but https://csis.myclimateservice.eu/study/30/step/1613/view/table and https://csis.myclimateservice.eu/study/14/step/1651/view/table show exactly the same data. 

One is in Naples and the other in Vienna. Not good. Not good at all. :-(

The same is true also for the impact tables

https://csis.myclimateservice.eu/study/14/step/1650/view/table
https://csis.myclimateservice.eu/study/30/step/1612/view/table

E.g., sort by population and this is what you will see:
![image](https://user-images.githubusercontent.com/2961790/66268431-a9260100-e83d-11e9-9068-eaccad869680.png)
![image](https://user-images.githubusercontent.com/2961790/66268464-d8d50900-e83d-11e9-8470-ce235dd1d0e3.png)

**Comment by p-a-s-c-a-l** [comment]
> https://csis.myclimateservice.eu/study/14/step/1650/view/table
> https://csis.myclimateservice.eu/study/30/step/1612/view/table

I don't know what happened, but this really bad: 

![grafik](https://user-images.githubusercontent.com/1788226/66292127-d1683b00-e8e3-11e9-97fa-2f9776922926.png)

**Comment by humerh** [comment]
As you see in the screenshot the displayed data are in both cases from Emikat-ID=3189 (SZM_SZENARIO_REF).
Maybe the message last week (about removing the filter SZ_ID=....) was not correct.
I have to check this on my side. But I am sure in this area is the problem.

**Comment by p-a-s-c-a-l** [comment]
As you can see, the requests to EMIKAT API contain different scenario ids (3174, 3210). So the problem is most likely on EMIKAT side.

> https://csis.myclimateservice.eu/study/14/step/1650/view/table

Period: historical, Scenario: Historical, Frequency: yearly, Variant: no Adaptation Options
https://service.emikat.at/EmiKatTst/api/scenarios/3174/feature/view.2975/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Frequent%27


> https://csis.myclimateservice.eu/study/30/step/1612/view/table

Period: historical, Scenario: Historical, Frequency: yearly, Variant: no Adaptation Options
https://service.emikat.at/EmiKatTst/api/scenarios/3210/feature/view.2975/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Frequent%27

**Comment by p-a-s-c-a-l** [comment]
> As you see in the screenshot the displayed data are in both cases from Emikat-ID=3189

In which screenshot? The screenshots above (https://github.com/clarity-h2020/table-components/issues/20#issue-503023417) show the ids 3174 and 3210.

**Comment by humerh** [comment]
You see it in the displayed table. The last column is SZM_SZENARIO_REF (which should be the same as the 'emikatId')

**Comment by humerh** [comment]
I updated the server and the error should be corrected!

**Comment by DenoBeno** [comment]
Hu. Good.

Don't do this to me. I'm not so young anymore...

:-D

**Comment by DenoBeno** [comment]
I'm not sure if this is correct data now or not, but it would be nice if the coordinates we show would all be in the same coordinate system:

https://csis.myclimateservice.eu/study/35/step/1524/view/table

![image](https://user-images.githubusercontent.com/2961790/66314373-3a67a700-e914-11e9-9abc-f2b7a412cbf2.png)

Same for exposure and for impact table. 

but 
https://csis.myclimateservice.eu/study/35/step/1530/view/table

![image](https://user-images.githubusercontent.com/2961790/66314462-5d925680-e914-11e9-98e5-c37225eec3c1.png)
